POST https://have-drivers.herokuapp.com/driver/login/ HTTP/1.1
Content-Type : application/json

{
    "username":"9897571117",
    "password":"mohan"
}

###profile

POST https://have-drivers.herokuapp.com/driver/profile/ HTTP/1.1
Content-Type: application/json

{
	"username":"5454699545","password":"123456789","first_name":"ishendra","last_name":"Pratap","email":"ishnedra@gmail.com",
	"address":"bahadurpur sahar auraiya","vehicle_number":8574,"locations":"kanpur","age":21,"mobile":343434343
}



### profile get

GET https://have-drivers.herokuapp.com/driver/profile/?username=9634824810  HTTP/1.1

### Directions GET

GET https://maps.googleapis.com/maps/api/directions/json?origin=gwalior&destination=agra&key=AIzaSyDz_VDMBsGjRBG_VtgStOlcb-MIGfPTL58